[build]
  publish = "."
  command = "# no build command"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify Identity
[template.environment]
  NETLIFY_IDENTITY = "enabled"

# Enable Git Gateway
[template.environment]
  NETLIFY_GIT_GATEWAY = "enabled"