backend:
  name: github
  repo: your-github-username/your-repo-name
  branch: main
  base_url: https://api.netlify.com

media_folder: "assets/img/portfolio"
public_folder: "/img/portfolio"

collections:
  - name: "portfolio"
    label: "Portfolio Items"
    folder: "_portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Corporate Uniforms", "Event Apparel", "Bespoke Clothing"]}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}